In [1]:
import pandas as pd
import math
import csv
from sklearn import preprocessing
import random
import numpy as np

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [2]:
def knn(k,trainingSet , testSet,trainingClass,testClass,actual=[],predicted=[]):
    #test_data=[[]]
    for test_instance,tes_instance in zip(testSet,testClass):
        row3=[]
        row2=[]
        row1=[]
        for training_instance,train_instance in zip(trainingSet,trainingClass):
            #print(training_instance[0])
            #dist = abs(float(test_instance[0]) - float(training_instance[0]))
            distance=pow((float(test_instance[0]) - float(training_instance[0])), 2)
            dist=math.sqrt(distance)
            row_dict={'predicted_class':train_instance,'actual_class':tes_instance,'value':dist}
            row1.append(row_dict)
        #print(row1)
        row2=sorted(row1, key = lambda i: i['value'])
        #print(len(row2))
        
        for i in range(k):
            row3.append(row2[i])
        #test_data.append(row3)

    
        #list2 = [e for e in test_data if e]
        test_array=np.asarray(row3)
        
        #for i in test_array:
            #print(i)
        healthy_count=0
        unhealthy_count=0
        for j in test_array:
            
            if(j.get('predicted_class')=='1'):
                healthy_count+=1
            else:
                unhealthy_count+=1
                #late_count+=1

        if(healthy_count >= unhealthy_count):
            predicted.append('1')
            actual.append(j.get('actual_class'))
        else:
            row3=[]
            row2=[]
            row1=[]
            
            for training_instance,train_instance in zip(trainingSet,trainingClass):
                
                distance=0
                for x in range(1,9):
                    distance += pow(float(test_instance[x]) - float(training_instance[x]), 2)
                dist=math.sqrt(distance)
                row_dict={'predicted_class':train_instance,'actual_class':tes_instance,'value':dist}
                row1.append(row_dict)
            
            row2=sorted(row1, key = lambda i: i['value'])
               
            for i in range(k):
                row3.append(row2[i])

            test_array=np.asarray(row3)
                
            early_count=0
            late_count=0
                #healthy_count=0
            for j in test_array:
                if(j.get('predicted_class')=='0'):
                    early_count+=1
                elif(j.get('predicted_class')=='2'):
                    late_count+=1

                
            if(early_count >= late_count):
                predicted.append('0')
                actual.append(j.get('actual_class'))
            else:
                predicted.append('2')
                actual.append(j.get('actual_class'))
    print(actual, predicted)

In [3]:

def loadDataset(filename, split, trainingSet=[] , testSet=[], trainingClass=[],testClass=[]):
    arr=[]
    names = ['sumValue','contrast', 'dissimilarity', 'homogeneity', 'ASM', 'energy','hue','value', 'saturaton','label']
    dataset = pd.read_csv(filename,names=names)
    
    X = dataset.iloc[:, :-1].values
    y = dataset.iloc[:, 9].values

    print('length of dataset', len(dataset))
    
    for x in range(1,len(dataset)):
        if random.random() <= split:
        #if x <= 1706:
            trainingSet.append(X[x])
            trainingClass.append(y[x])
        else:
            testSet.append(X[x])
            testClass.append(y[x])


    


In [4]:
actual=[]
predicted=[]

testClass=[]
trainingClass=[]
trainingSet=[]
testSet=[]
data = pd.read_csv('glfeat.csv')
loadDataset('glfeat.csv', 0.66, trainingSet, testSet,trainingClass,testClass)


length of dataset 2609


In [17]:
knn(301,trainingSet, testSet,trainingClass,testClass,actual,predicted)


['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',

In [18]:
results = confusion_matrix(actual, predicted) 
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :',accuracy_score(actual, predicted))
print('Report : ')
print(classification_report(actual, predicted))

Confusion Matrix :
[[925  44  87]
 [ 17 394 165]
 [218  89 713]]
Accuracy Score : 0.7662141779788839
Report : 
              precision    recall  f1-score   support

           0       0.80      0.88      0.83      1056
           1       0.75      0.68      0.71       576
           2       0.74      0.70      0.72      1020

    accuracy                           0.77      2652
   macro avg       0.76      0.75      0.76      2652
weighted avg       0.76      0.77      0.76      2652



In [19]:
# mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
#           {'a': 100, 'b': 200, 'c': 300, 'd': 400},
#           {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000 }]
# df = pd.DataFrame(mydict)
# df


In [20]:
print('Accuracy Score :',accuracy_score(actual, predicted))

Accuracy Score : 0.7662141779788839


In [9]:
data = pd.read_csv('glfeat.csv')

In [10]:
data.head()

Unnamed: 0  Unnamed: 0.1    sumValue    contrast  dissimilarity  \
0           0             0   78.383672  412.323589      11.591734   
1           1             1  107.763630  600.402218      14.192540   
2           2             2   80.305666  582.678427      14.162298   
3           3             3   92.363413  408.552419      12.177419   
4           4             4  108.226614  698.560484      16.943548   

   homogeneity       ASM    energy        hue      value   saturaton  label  
0     0.155581  0.001368  0.036984  90.853516  54.087891  135.036133      0  
1     0.143442  0.001561  0.039508  72.970703  62.058594  159.561523      0  
2     0.174249  0.001931  0.043941  77.554688  49.791016  150.990234      0  
3     0.145949  0.001390  0.037285  76.940430  62.466797  145.730469      0  
4     0.134688  0.001207  0.034745  64.431641  93.595703  128.674805      0

In [11]:
data.iloc[:,:-1]

Unnamed: 0  Unnamed: 0.1    sumValue    contrast  dissimilarity  \
0              0             0   78.383672  412.323589      11.591734   
1              1             1  107.763630  600.402218      14.192540   
2              2             2   80.305666  582.678427      14.162298   
3              3             3   92.363413  408.552419      12.177419   
4              4             4  108.226614  698.560484      16.943548   
...          ...           ...         ...         ...            ...   
2603        2603          2603   89.258053  507.433468      13.131048   
2604        2604          2604  150.469266  368.322581      11.131048   
2605        2605          2605  191.984374  169.987903       8.423387   
2606        2606          2606  164.590401  483.760081      12.477823   
2607        2607          2607   86.579443  139.032258       7.727823   

      homogeneity       ASM    energy         hue      value   saturaton  
0        0.155581  0.001368  0.036984   90.853516  54.087891  135.036133  
1        0.143442  0.001561  0.039508   72.970703  62.058594  159.561523  
2        0.174249  0.001931  0.043941   77.554688  49.791016  150.990234  
3        0.145949  0.001390  0.037285   76.940430  62.466797  145.730469  
4        0.134688  0.001207  0.034745   64.431641  93.595703  128.674805  
...           ...       ...       ...         ...        ...         ...  
2603     0.171011  0.001500  0.038729   81.120117  54.495117  137.317383  
2604     0.160465  0.001457  0.038174  100.448242  54.745117  128.080078  
2605     0.157724  0.001447  0.038040  100.260742  56.724609  135.189453  
2606     0.157656  0.001246  0.035297   59.673828  75.135742  134.467773  
2607     0.178997  0.001929  0.043917   90.746094  63.737305  146.779297  

[2608 rows x 11 columns]

In [12]:
data.iloc[:,10]

0       135.036133
1       159.561523
2       150.990234
3       145.730469
4       128.674805
           ...    
2603    137.317383
2604    128.080078
2605    135.189453
2606    134.467773
2607    146.779297
Name: saturaton, Length: 2608, dtype: float64